### Get KEK list from DEK Registry
GET {{sr-url}}/dek-registry/v1/keks HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}

### Get DEK Policy
GET {{sr-url}}/dek-registry/v1/policy HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}
