### Get KEK list from DEK Registry
GET {{sr-url}}/dek-registry/v1/keks HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}

### Get KEK Policy
GET {{sr-url}}/dek-registry/v1/policy HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}

### Get DEK
GET {{sr-url}}/dek-registry/v1/keks/{{kek-name}}/deks/raw.recipes-value HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}

### Get DEK-Shared
GET {{sr-url}}/dek-registry/v1/keks/{{kek-name-shared}}/deks/raw.orders-value HTTP/1.1
Authorization: Basic {{sr-api-key}}:{{sr-api-secret}}
