#!/bin/bash
# Usage: ./create-gcp-apps.sh <gcp-region>

# Check if a region was provided as an argument
if [[ $# -lt 1 || -z "$1" ]]; then
  echo "❌ gcp region not specified."
  echo "Usage: $0 <gcp-region>"
  exit 1
fi
GCP_REGION="$1"
GCP_PROJECT_ID="$2"

TFVARS_FILE="gcp-terraform.auto.tfvars"
TFVARS_SECRET_FILE="gcp-terraform-secret.auto.tfvars"

echo "# Auto-generated by create-gcp-apps.sh" > "$TFVARS_FILE"
# Get or generate UNIQUE_ID from tfvars file
if grep -q '^unique-id[[:space:]]*=' "$TFVARS_SECRET_FILE" 2>/dev/null; then
  UNIQUE_ID=$(grep '^unique-id[[:space:]]*=' "$TFVARS_SECRET_FILE" | head -n1 | awk -F= '{gsub(/^[ \t"]+|[ \t"]+$/, "", $2); print $2}')
else
  UNIQUE_ID=$(uuidgen | tr '[:upper:]' '[:lower:]' | cut -c1-6)
  echo "unique-id = \"$UNIQUE_ID\"" >> "$TFVARS_SECRET_FILE"
fi

echo "cloud = \"GCP\"" >> "$TFVARS_FILE"
echo "region = \"$GCP_REGION\"" >> "$TFVARS_FILE"
echo "gcp-project-id = \"$GCP_PROJECT_ID\"" >> "$TFVARS_FILE"

echo "✅ Done. Outputs written to $TFVARS_FILE"
