#!/bin/bash
# Usage: ./create-aws-apps.sh <aws-region>

# Check if a region was provided as an argument
if [[ $# -lt 1 || -z "$1" ]]; then
  echo "❌ AWS region not specified."
  echo "Usage: $0 <aws-region>"
  exit 1
fi
AWS_REGION="$1"

TFVARS_FILE="aws-terraform.auto.tfvars"
TFVARS_SECRET_FILE="aws-terraform-secret.auto.tfvars"

echo "# Auto-generated by create-aws-apps.sh" > "$TFVARS_FILE"
# Get or generate UNIQUE_ID from tfvars file
if grep -q '^unique_id[[:space:]]*=' "$TFVARS_SECRET_FILE" 2>/dev/null; then
  UNIQUE_ID=$(grep '^unique_id[[:space:]]*=' "$TFVARS_SECRET_FILE" | head -n1 | awk -F= '{gsub(/^[ \t"]+|[ \t"]+$/, "", $2); print $2}')
else
  UNIQUE_ID=$(uuidgen | tr '[:upper:]' '[:lower:]' | cut -c1-6)
  echo "unique_id = \"$UNIQUE_ID\"" >> "$TFVARS_SECRET_FILE"
fi

echo "cloud = \"AWS\"" >> "$TFVARS_FILE"
echo "region = \"$AWS_REGION\"" >> "$TFVARS_FILE"

echo "✅ Done. Outputs written to $TFVARS_FILE"
